# Generated by Django 4.2.9 on 2024-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
