# Generated by Django 4.2.9 on 2024-01-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfsite', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfsite.projectitem', verbose_name='Проект'),
        ),
    ]
