# Generated by Django 4.2.9 on 2024-01-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfsite', '0005_comment_delete_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='project',
        ),
    ]
