# Generated by Django 4.2.9 on 2024-01-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfsite', '0006_rename_post_comment_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
